### ISSUE TITLE
[Suggestion] Add Nitrokey to 2FA resources section

### ISSUE THREAD

**Issue by IHateTheProgrammingClass** [techlore/website#12]
Nitrokey.com is a well trusted security hardware maker to my knowledge. Their 2FA key could be a good addition in the resources.

**Comment by MrMuffinIsTaken** [comment]
I think this would be a great addition to the website. But it's up to the team of techlore to select if they would like to list it on their website or not.

**Comment by IHateTheProgrammingClass** [comment]
I agree. That's why I made the issue.

**Comment by MrMuffinIsTaken** [comment]
@henryistaken what's your thoughts on this?

**Comment by henryistaken** [comment]
Nitrokey has been added to our resources as of the latest commit, thanks everyone:
https://github.com/techlore/website/commit/452cd459d1d3f73c11144ba9453a4f8b7a637acc
