### ISSUE TITLE
Startpage now privately proxies both Google and Bing search results

### ISSUE THREAD

**Issue by 8pen-s8urce** [techlore/website#120]
Source: https://support.startpage.com/hc/en-us/articles/4522435533844-What-is-the-relationship-between-Startpage-and-your-search-partners-like-Google-and-Microsoft-Bing

This change should be reflected in the Startpage description in the Techlore Resources webpage.

**Comment by rollsicecream** [comment]
I will do a PR very soon for that.

**Comment by rollsicecream** [comment]
Done!

**Comment by henry-fisher** [comment]
Thanks @rollsicecream <3 Just merged: 
https://github.com/techlore/website/pull/121
