### ISSUE TITLE
Proton VPN total servers: doubts and corrections

### ISSUE THREAD

**Issue by 8pen-s8urce** [techlore/website#138]
The Proton VPN webpage describing its servers includes the following server statistics, among others:

8633 servers
109 Secure Core servers
7372 Plus servers

Source for these statistics: https://protonvpn.com/vpn-servers (only shows the amount of total Proton VPN servers with cookies and JavaScript enabled, at least to me when using Brave on Android).

My assumptions (PLEASE correct me if you think that any of these assumptions is wrong or if more research needs to be done):
• These statistics are correct;
• The 109 Secure Core servers aren't included in the 7372 Plus servers;
• All Secure Core and Plus servers mentioned are available to all paid Proton VPN subscribers;
• The total amount of Proton VPN servers is equal to the sum of Secure Core servers, Plus servers and Free servers.

The following should be true:

Free servers=8633-(109+7372)=8633-7481=1152
Plus/Unlimited servers=7372+109=7481

So, what should go to the chart?

Also, the total of "Plus/Unlimited" servers written in the Techlore VPN Toolkit is meant to represent all "Plus/Unlimited" only servers (total amount of Proton VPN servers minus free servers, includes Secured Core servers) or the total amount of Proton VPN servers available to paid subscribers, including free servers?

One way to avoid confusion would be to only list on the Techlore VPN Toolkit the total amount of Proton VPN servers, also making the chart more uniform as Proton VPN is currently the only VPN provider with differences between the Plus/Unlimited and free plans included in there.

If my proposal from the previous paragraph gets accepted, the same simplification process could be applied to the Proton VPN entries in the "Total Countries" and "Simultaneous Devices" categories, maybe even to the iVPN entry in the "Simultaneous Devices" category, but that is another matter.

Any feedback is welcome. 🙂

**Comment by henry-fisher** [comment]
We'll definitely keep this simple as there's no need to complicate this because one VPN provider has a somewhat complicated subscription. 
<img width="922" alt="image" src="https://github.com/user-attachments/assets/8e1dba00-f81b-4e46-a686-c69cd040b629">

We'll just go off the total number 9,286 which I can update.

**Comment by henry-fisher** [comment]
Fixed: https://github.com/techlore/website/pull/162
