### ISSUE TITLE
Mention DoH and DoT support in Windscribe

### ISSUE THREAD

**Issue by gracjankn** [techlore/website#143]
The VPN Toolkit states that Windscribe only supports IPv4 for custom DNS, but this information is outdated.

Windscribe states in [their supports article](https://windscribe.com/knowledge-base/articles/how-to-use-custom-dns-in-the-windscribe-app/#:~:text=Now%20you%20will%20have%20the%20option%20to%20enter%20the%20IP%20for%20the%20DNS%20resolver%20you'd%20like%20to%20use.%20In%20addition%20to%20legacy%20(IPv4)%20DNS%20resolvers%2C%20we%20have%20also%20added%20the%20ability%20to%20tunnel%20your%20DNS%20queries%20over%20DoH%20(DNS%20over%20HTTPS)%20or%20DoT%20(DNS%20over%20TLS)%20resolvers.):

> Now you will have the option to enter the IP for the DNS resolver you'd like to use. In addition to legacy (IPv4) DNS resolvers, we have also added the ability to tunnel your DNS queries over DoH (DNS over HTTPS) or DoT (DNS over TLS) resolvers.

**Comment by henry-fisher** [comment]
Updated! Thanks for reporting the update :) 
https://github.com/techlore/website/commit/b7249e9b8e43460b4d4424f283c2e8389d8b89b5
