### ISSUE TITLE
Add Divested tools to resources

### ISSUE THREAD

**Issue by SkewedZeppelin** [techlore/website#15]
I offer DivestOS, an Android ROM that provides long term device support along with enhanced privacy and security.
Website: https://divestos.org
Source: https://gitlab.com/divested-mobile
Project History: https://divestos.org/index.php?page=history

I also offer Mull, a Firefox for Android fork that is hardened for privacy out of the box.
Download: https://f-droid.org/en/packages/us.spotco.fennec_dos/
Source: https://gitlab.com/divested-mobile/mull-fenix
Release Comparison: https://divestos.org/misc/ffa-dates.txt

Any questions welcome.

fwiw, I am not a company and I am not selling anything.

**Comment by jonaharagon** [comment]
What would you consider the main differentiating features from LineageOS (from a long-term support perspective) or CalyxOS (from a security/privacy perspective) to be, out of curiosity?

**Comment by SkewedZeppelin** [comment]
CalyxOS has limited device support.
LineageOS doesn't offer bootloader locking or verified boot or extensive CVE patching or support for many of these older devices.
Please see https://divestos.org/index.php?page=technical_details for the bulk of differences to LineageOS.

Also relevant: https://github.com/privacyguides/privacyguides.org/discussions/58

**Comment by henryistaken** [comment]
Thanks for the patience!

I just went ahead and listed DivestOS on our resources page in the latest commit: https://github.com/techlore/website/commit/5e4a98ec6295fd9b510845069d454243d4be0109

**Comment by SkewedZeppelin** [comment]
Thank you!
