### ISSUE TITLE
Should Onion Browser be recommended?

### ISSUE THREAD

**Issue by jizyy6c1s** [techlore/website#16]
Onion Browser has had [an issue](https://github.com/OnionBrowser/OnionBrowser/issues/117) with IP leaks via WebRTC since 2018. Should it really be listed under iOS browsers on Resources?
(made on behalf of one Happy Henry)

**Comment by henryistaken** [comment]
While that's definitely a cause for concern, it's still the recommended approach to using Tor on iOS (As per the Tor Project themselves)

We'll keep an eye on the issue and see if there are any better alternatives down the road. We can also mention this once we can add some notes on our resources.
