### ISSUE TITLE
Use Sigle

### ISSUE THREAD

**Issue by Loki-L1130** [techlore/website#17]
Recently Henry wrote an article on Medium - https://medium.com/@henryistaken/the-real-privacy-enemy-is-ourselves-dc2188ad7eeb . 

I think supporting medium is like more towards centralization and with no Privacy.

I suggest the team to use https://Sigle.io which is decentralized Blogging platform and mostly like medium. It is getting an Big update in Weeks.

**Comment by Loki-L1130** [comment]
I am telling about it here, Because I found no way to speak as I declined the use of twitter.

**Comment by henryistaken** [comment]
A) That blog is technically my personal blog, not Techlore's. This isn't the place for it.
B) Even if it was Techlore's, this isn't the place for it. This is a GitHub repo for the Techlore site.
