### ISSUE TITLE
Issue with vpn review table extra table showing with 404 link

### ISSUE THREAD

**Issue by mendelsphotography** [techlore/website#27]
Hi, So as I was looking at the VPN review page, I saw there was an extra empty table at the bottom with 2 links: 1 link for a normal one and 2 for an Affiliate link. They both go to this page, which does not exist and looks to me like a JS Error Probloy for some reason going to a page. https://techlore.tech/undefined that's where it goes to.
I did some digging into the code and looked and tried editing the code to see if I can figure out what's going on here.
After my own research, this is what I came up with. For some reason, in the process of converting to JSON it adds a blank extra table at the bottom. Maybe in the JavaScript somewhere it's somehow adding those links. Not sure, but it's adding them. Which leads to 404.

**Comment by henryistaken** [comment]
Aware of the issue, will be taking a look at it in the near future as I update some of the VPN tools

**Comment by henryistaken** [comment]
Have confirmed that this has been fixed. Was actually caused by an extra line in the CSV file

**Comment by mendelsphotography** [comment]
Thanks for fixing it.
