### ISSUE TITLE
Suggestion: Add Column for VPN with "Connect on Boot" feature

### ISSUE THREAD

**Issue by 8227846265** [techlore/website#31]
Please add a column that shows which VPN has a `Connect on Boot` feature.

What's Connect on Boot?

- This allows the VPN program to connect during boot state, instead of connecting after the computer is successfully logged in and the VPN program launches (e.g. Connect on Launch),

Why Connect on Boot is important?

- If you have Kill Switch enabled. The standard experience of a VPN User is that they won't be able to browse the internet until the VPN program launches and connected after successfully logged in to the computer.

- This produces a disconnected state of about 5 seconds to 1 minute or more depending on the following factors
A. If the computer hardware spec is good enough
B. The number of startup programs on queue ahead of the VPN program

- This experience repeats on every single reboot of your computer.

With Connect on Boot, all the problem above is non-existent and you can ensure that your computer is always connected to the VPN server from the first 1 second you successfully logged in your computer.

Which VPN providers have Connect on Boot feature?

- Mullvad
This could be enabled by going to Settings > Preferences and enable `Launch app on start-up` and `Auto-connect`. This trigger the hidden setting "Connect on Boot" to be enabled by default.

- VyprVPN
This could be enabled by going to Settings > Startup Options > enable `Connect on Boot`

**Comment by henry-fisher** [comment]
Finally implemented this https://github.com/techlore/website/commit/ab95647d72545c4b9aff2d93f57d61e3044ffa19

With that said, it's missing a lot of data—so I encourage people to contribute to help us find these data points!
