### ISSUE TITLE
[Suggestion] Section with answers for common counterarguments against privacy.

### ISSUE THREAD

**Issue by justaguydoinghisstuff** [techlore/website#4]
Hello,
may i suggest that it would be great if among all the other resources you put out for this community we have a community driven Q&A section with answers to the most commons responses like "I dont care about privacy", "If giving my data means the service is free im fine with it" or "im fine with them having my data" among others.
My idea was something like Plexus where people would pitch in their counterarguments. 
Im sure that the team might be busy with so many projets but it would be interesting to see this in the future, as there are probabbly more people like me that start to understand the need for privacy but cant quite explain it to people,without them loosing interst.

The idea came up after watching GoIncognito 6.9

**Comment by techlore-official** [comment]
Will keep this issue open and explore the possibility of adding it down the road.

**Comment by techlore-official** [comment]
Neat idea, will keep the issue open and we'll explore this down the road.

**Comment by henryistaken** [comment]
Coming back around to this, I think this may be something better suited for our video content, rather than a website project. I've added it to our video ideas. Thanks again for the suggestion!
