### ISSUE TITLE
[VPN Chart] IVPN Removed Port Forwarding

### ISSUE THREAD

**Issue by barbiehunter** [techlore/website#45]
In the VPN list IVPN still has port forwarding, which is only for active customers and no new ones. Either remove it when it is officially no longer available for all or in the next update of the VPN charts.

Source: [IVPN Blog Post](https://www.ivpn.net/blog/gradual-removal-of-port-forwarding/)

**Comment by henry-fisher** [comment]
https://github.com/techlore/website/pull/43
Someone already pushed this update :) Thanks for reporting it!
