### ISSUE TITLE
Move "use only private and secure browsers" to Zone 1 (SPA)

### ISSUE THREAD

**Issue by IronMaltese** [techlore/website#48]
I have found that the easiest step to make someone more private is getting them to start using a private web browser. For someone willing to take a privacy and security quiz, they probably want to be more private and would be willing to download a private web browser, since it's easier than buying a shredder, safe or even configuring a router

Also Zone 3 has this question, and I believe the question in Zone 3 should be "Only use Tor for web browsing" since that's such an extreme threat model

I feel like this question should be moved, but if you disagree let me know

**Comment by henry-fisher** [comment]
Merged into https://github.com/techlore/website/issues/47
