### ISSUE TITLE
Create separate question for email aliasing (SPA)

### ISSUE THREAD

**Issue by IronMaltese** [techlore/website#49]
There's already a question about phone number aliasing in Zone 2, but a separate question should be added for email aliasing, since email aliasing is a lot easier than phone number aliasing

This question can even be put in zone 1 because it's a decently streamlined experience to create masked emails, and duckduckgo even allows unlimited masked emails for free, for anyone that doesn't want to pay for the other alternatives

**Comment by henry-fisher** [comment]
Merged into https://github.com/techlore/website/issues/47
