### ISSUE TITLE
Mention Brave's forget this site feature in a link (SPA)

### ISSUE THREAD

**Issue by IronMaltese** [techlore/website#50]
This is a premature issue to be opened in this repository, since  the feature hasn't released yet, but Brave's "forget this site" feature will make clearing cache and cookies so much easier and user friendly that I feel it has to be mentioned in Zone 1 next to "Clear device temporary data" and "frequently clear or never store browsing data"

**Comment by henry-fisher** [comment]
Merged into https://github.com/techlore/website/issues/47
