### ISSUE TITLE
Differentiate between user friendly and maximum security software (Privacy Resources)

### ISSUE THREAD

**Issue by IronMaltese** [techlore/website#51]
I like the system on the Privacy resources page where you recommend your favorite products with a star, but I believe this approach is still too general for a few cases such as Briar and Signal both having stars next to them, so these products should be properly differentiated, since Briar is a lot harder for the average person to use, while Signal is more user-friendly with less security/privacy features than Briar.

We can differentiate recommendations between ones made for maximum privacy and ones made for maximum security/privacy by prefacing in the popup that shows up when the visitor hovers over the symbol, that the software may have features that limit usability

- For Tor, this can say that the browser can be slow, some websites block tor, and/or the browser clears data on exit

- For Briar it can say that the app has to run constantly for messages to be recieved and/or this wastes battery

- For Mullvad we can potentially say it clears data on exit

**Comment by jonaharagon** [comment]
Limitations like the 3 examples you mentioned here seem (IMHO) to be relatively self-explanatory when you visit the project page we link to. I'm not sure if it makes sense to essentially duplicate project documentation here?

This is also stuff that is of course typically covered in Henry's video reviews. Maybe the YouTube links should be presented first in these lists instead of last (both to give that relevant information right away, and also just to have a more consistent look across the page)?

**Comment by henry-fisher** [comment]
As stated at the top, "[star] marks a favorite. They don't represent every threat model and shouldn't be over-analyzed."

This isn't really meant to be a tool to directly tell people anything aside from some favorite services of ours so people see an inside look of what's enjoyed.

Regarding trying to speak to more nuanced differences between services, that's not really the purpose of the Techlore resources page, hence why it links to videos, links to each individual service, and links to external sources at the bottom which already do this work you're describing. My goal isn't to escalate this into an entirely written guide of all Techlore video content. It's just a centralized hub to quickly showcase numerous services.

> Maybe the YouTube links should be presented first in these lists instead of last (both to give that relevant information right away, and also just to have a more consistent look across the page)?

I'll play around with this and see how it looks.
