### ISSUE TITLE
Wrong link in https://techlore.tech/resources.html page

### ISSUE THREAD

**Issue by romitrajsahu** [techlore/website#6]
![Screenshot_20210612_174542](https://user-images.githubusercontent.com/81353919/121775679-b82e8c00-cba6-11eb-8fce-9dd73ff12a29.png)

In the Resources page, the VPN Finder Tool 'Visit' link redirects to VPN Review Tool page instead of VPN Finder Tool Page.

Please fix this.

**Comment by techlore-official** [comment]
https://github.com/techlore/website/commit/534b7e80f2ee9c5297f5e9cbaae1b181d350c552
Fixed!
