### ISSUE TITLE
Change the number of NordVPN servers and countries in the VPN toolkit.

### ISSUE THREAD

**Issue by ghost** [techlore/website#64]
Hello, 

NordVPN has 5664 servers worldwide and 59 countries

Quoting https://nordvpn.com/servers

> Choose from NordVPN’s 5664 ultra-fast servers in 59 countries.

The VPN tookit says 

> Total servers : 5611      
> Total countries : 60

So please, make this change to reflect this.

Thanks.

**Comment by henry-fisher** [comment]
Thanks for the patience! 
Fixed: https://github.com/techlore/website/commit/643c20ed5ae85d3ead77773765f5d5dbaf5a500d
