### ISSUE TITLE
[VPNChart] Perfect Privacy wrong info.

### ISSUE THREAD

**Issue by barbiehunter** [techlore/website#65]
I'm a fan of Perfect Privacy, but I noticed one wrong info. It says that Perfect Privacy has Transparency Report, but this is not true. I brought this up a few months ago and it may come in the future, but isn't on the Website atm

Source: [Perfect Privacy Forum (German)](https://board.perfect-privacy.com/threads/wir-sind-umgezogen.5745/#post-36428)

> We can do a transparency report, but there is really not much to report.

PS: May mention that they actually got Open source software, but for Wndows Only (and soon _Linux_ aswell, but no eta when).

**Comment by henry-fisher** [comment]
Thanks for the notice, will update this as soon as possible

**Comment by henry-fisher** [comment]
https://github.com/techlore/website/commit/643c20ed5ae85d3ead77773765f5d5dbaf5a500d
Fixed :)
