### ISSUE TITLE
Add Proton Drive to the cloud services section in resources

### ISSUE THREAD

**Issue by MooseExplorer637** [techlore/website#72]
Now that Proton Drive has implemented both the Windows and macOS apps and the Linux client is probably coming at some point, I think we should add Proton Drive as a recommendation. I don't think the lack of a Linux client should be the reason to exclude Proton Drive because you can still access it through the web browser, which is also the only way to access Cryptee, a current top recommendation.

**Comment by rollsicecream** [comment]
> I don't think the lack of a Linux client should be the reason to exclude Proton Drive.

Well, actually a Linux client should be important, Linux is the recommended OS for people that wants to protect your privacy. If you are a new Linux user and your Proton Drive isn't available on your platform, you will be kinda pissed off.

> because you can still access it through the web browser

While this is true, you will lose automatic backups, the ability to put files directly from your file explorer. And you have to log in every time you want to add a file, which is widely incovenient.

> Cryptee, a current top recommendation

At least, they do reasons of 'why'

https://crypt.ee/download#why-not-app-stores

**Comment by MooseExplorer637** [comment]
I agree that a Linux client should be important, and Proton will probably add it at some point. However, a far more critical feature should be the strong security that Proton Drive offers, something that Mega, another recommendation, isn't known for. Recommending Mega but leaving Proton Drive out is perhaps the biggest issue with Techlore's recommendations at the moment, and the added "star" gives a false impression that Mega would be a particularly excellent cloud service provider in the privacy and security space when this just isn't true. However, this issue should be discussed separately.

**Comment by rollsicecream** [comment]
Maybe why it isn't added for now is this criteria?

![Capture d’écran du 2023-12-18 20-42-22](https://github.com/techlore/website/assets/153316540/9af1b55b-177b-4a90-995e-086ac509ae79)

I'm not sure though.

**Comment by MooseExplorer637** [comment]
I don't think that should be a limiting factor since Proton is a well-known company in the privacy space and operated there for years. So, the risk that they would eliminate Drive seems highly unlikely. Also, Techlore already recommends Proton Pass even though it was launched this year.

**Comment by henry-fisher** [comment]
https://github.com/techlore/website/commit/62933d14bb2073d619265dd98806604adefd3d0a
Thanks for the suggestion you two. Originally Drive was excluded because it didn't feel ready enough to be suggested without too many usability caveats, but it feels more developed now and I've gone ahead and listed it. :)
