### ISSUE TITLE
Add ente Auth to resources page (2FA)

### ISSUE THREAD

**Issue by rollsicecream** [techlore/website#82]
Hello Henry!

Can ente Auth be added to the resources page (2FA category). It seems like it passes all the criteria. It's all-open-source, available on F-Droid and easy to use. All with E2EE, it can even be used accountless (so without an ente account). It's from the people who created ente, the photo management service.

It's a really great alternative for people on iOS, as Raivo is no more there.

Thanks.

**Comment by henry-fisher** [comment]
<img width="231" alt="image" src="https://github.com/techlore/website/assets/64515030/1962140b-cc7c-4b8d-bab1-bced0b3d4b9a">
Actually funny enough this has been on my to-do for a while. I'm still looking into it but will update this issue as time opens up!

**Comment by henry-fisher** [comment]
Thanks so much @jordan-warne for taking care of this!
